const factsObject = {
    factcount: "1000",
    facts: [
      "$30 of raw popcorn translates into $3,000 in sales at movie theaters",
      "'Barack Obama' born August 4 1961 was the 44th President of the United States.",
      "'Bookkeeper' and 'bookkeeping' are the only 2 words in the English language with three consecutive double letters",
      "'Canberra' is the capital of 'Australia'.",
      "'Coast Redwood' tree is the world's tallest tree (371 ft) in Redwood National Park California United States",
      "'Dina Thanthi' was founded by S. P. Adithanar a lawyer trained in Britain and practised in Singapore with its first edition from Madurai in 194",
      "'fan' is short for 'fanatic'",
      "'High Street Phoenix' in mumbai is the india's largest shopping mall with 3300000 sq ft whereas 'Express Avenue (Royapettah Chennai / Under construction)' will be the largest in south india with '1500000 sq ft'.",
      "'Jana Gana Mana' was officially adopted by the Constituent Assembly as the Indian national anthem on January 24 1952",
      "'Katharine Hepburn' has won four OSCAR awards more than any actor in film industry.",
      "'King Cobra' is the National Reptile of India.",
      "'Mango' is india's national fruit.",
      "'Mother India' (1957) was the first indian film to be nominated in Oscars in the best Foreign film category.",
      "'Mudskipper' fish can use their pectoral fins to walk on land.",
      "'Mumbai' is called as the 'Business Capital' of India.",
      "'Nitrous Oxide' is called as Laughing Gas.",
      "'orology' is the study of mountains",
      "'Skype Limited' was founded in 2003 by Swedish-born entrepreneur Niklas Zennström and the Dane Janus Friis.",
      "'South China Sea' is the largest sea in the world (2974600 sq km)",
      "'Sri Dalada Maligawa' temple in Kandy Sri Lanka also be called as “The temple of the teeth”. Kumarasami Kamaraj was born on 15-July-1903 and was chief minister of Tamil Nadu during 1954-196",
      "'Topolino' is the name for Mickey Mouse Italy",
      "'underground' is the only word that begins and ends with the letters 'und'",
      "'Vinoo Mankad' is the only indian cricket player to bat in all positions (1 to 11).",
      "-40 degrees Celsius is equal to -40 degrees Fahrenheit.",
      "1 billion snails are served in restaurants each year",
      "1 gigayear = 1,000,000,000,000 years",
      "1 googol is the number 1 followed by 100 zeros",
      "1 nautical knot equates to 1.852 Kph (1.150 mph)",
      "1 out of every 8 letters written is an e",
      "1 plain milk chocolate bar has more protein than a banana.",
      "1 square inch of human skin contains 625 sweat glands.",
      "10 of the tributaries flowing into the Amazon river are as big as the Mississippi river.",
      "10% of the Russian government's income comes from the sale of vodka.",
      "10% of with world's food supply is consumed by insects",
      "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
      "13 people die every year from vending machines",
      "15 million gallons of wine were destroyed in the 1906 San Francisco earthquake.",
      "160 cars can drive side by side on the Monumental Axis in Brazil, the world's widest road.",
      "17% of Intel employees are Indians.",
      "2 million hydrogen atoms would be required to cover a full stop (.)",
      "2 out of 5 people marry their first love",
      "2,500 newborn babies will be dropped in the next month.",
      "20% of China's plants are used in medicine",
      "20% of tuxedo rentals take place in May.",
      "20252 is Smokey the Bear's own zip code.",
      "21% of people don't make their bed in the morning",
      "22% of people skip lunch daily",
      '22-May-1990 Microsoft launched "Windows 0"O/s.',
      "23% of all photocopier faults worldwide are caused by people sitting on them and photocopying their butts.",
      "25% of your bones are located in your feet.",
      "3 teaspoons make up 1 tablespoon",
      "30% of people refuse to sit on a public toilet seats",
      "34% of Microsoft employees are Indians.",
      "36% of NASA employees are Indians.",
      "4.5 pounds of sunlight strike the Earth each day.",
      "40% of Amsterdam commuters get to work by bicycle",
      "40% of women have hurled footwear at a man.",
      "41% of the moon is not visible from earth at any time.",
      "42% of men and women 25% don't wash their hands after using a public toilet",
      "44% of people have broken a bone",
      "45% of people use mouthwash daily",
      "45,000 thunderstorms around the world occur every day",
      "53% of women don't leave home without makeup on",
      "55% of all movies are rated R",
      "56% of typing is completed by your left hand",
      "59% of people say that their average looking",
      "60 cows can produce a ton of milk each day",
      "68% of a Hostess Twinkie is air!",
      "7,000 new insect species are discovered every year.",
      "7-11 sells 10,000 pots of coffee an hour, every hour, every day.",
      "75% of people wouldn't give up their spouse for a night for a $1,000,000",
      "8% of people have an extra rib",
      "8.5 million tons of water evaporates from the Dead Sea every day",
      "80% of all people hit by lightning are men",
      "80% of burglaries are committed by people aged 13-21",
      "80% of millionaires drive used cars.",
      "80% of Publishers' Clearing House $10 million winners did not purchase any magazine subscriptions!",
      "80% of the world's food crops are pollinated by insects",
      "80% of the world's rose species come from Asia",
      "84% of a raw apple is water.",
      "85% of all Valentine's Day cards are purchased by women!",
      "85% of movie actors earn less than $5,000 a year from acting!",
      "85% of plant life is found in the ocean",
      "85% of women wear the wrong bra size",
      "9 out of 10 lightning strike victims survive!",
      "9% of people skip breakfast daily",
      "90% of women who walk into a department store immediately turn to the right.",
      "90% of all restaurants fail during their first year of operation.",
      "90% of all volcanic activity occurs in the ocean",
      "90% people depend on alarm clocks to wake up",
      "93% of households in Denmark consume wine (the highest% in the world with France second with 85% of households)",
      "96% of candles sold are purchased by women",
      "99% of people cannot lick their elbow.",
      '9th century chemist Jabir ibn Hayyan (known as "Geber"in Europe) is considered as "Father of chemistry".',
      '"Liberty Enlightening the World"is the official name of "Statue of Liberty".',
      '"Mobira Senator"is the first mobile phone model launched by Nokia in 198',
      "A 'face-off' in hockey was originally called a 'puck-off'.",
      "A 'jiffy' is an actual unit of time for 1/100th of a second!",
      "A 'jiffy' is an actual unit of time for 1/100th of a second",
      "a 1 minute kiss burns 26 calories",
      "a 1/4 of your bones are in your feet",
      "A 100-pound person on Earth would weigh 38 pounds on Mars.",
      "a 15th anniversary is called a quindecennial",
      "A B-25 bomber airplane crashed into the 79th floor of the Empire State Building on July 28, 1945.",
      "A baboon called Jackie became a private in the South African army in World War I.",
      "A baby eel is called an elver, a baby oyster is called a spat.",
      "a baby fetus develops fingerprints at eighteen weeks",
      "A baby octopus is about the size of a flea at birth.",
      "A ball of glass will bounce higher than a ball made of rubber.",
      "a banana contains 75% water",
      "a bear has 42 teeth",
      "a bear in hibernation loses up to 25% of its body weight",
      "A bird 'chews' with its stomach.",
      "a blue whale can go up to 6 months without eating",
      "a blue whale can weigh as much as 30 elephants and as long as 3 large tour buses",
      "A blue whale's aorta (the main blood vessel) is large enough for a human to crawl through.",
      "A blue whale's heart is the size of a Volkswagen Beetle!",
      "A Boeing 747 airliner holds 216,847 litres (57,285 gallons) of fuel",
      "A Boeing 747 airliner holds 57,285 gallons of fuel!",
      "A Boeing 747 airliner holds 57,285 gallons of fuel.",
      "a bowling pin will fall at a tilt of 7.5 degrees",
      "A broken clock is always right twice a day.",
      "a bumble bee flaps its wings at 160 times a second",
      "a camel can shut its nostrils during a desert sandstorm",
      "A car operates at maximum economy, gas-wise, at speeds between 25 and 35 miles per hour.",
      "A car traveling 100 mph would take more than 29 million years to reach the nearest star.",
      "a car travelling at 80kph (50mph) uses half its fuel to overcome wind resistance",
      "a cat can keep purring while inhaling and exhaling",
      "a cat has 32 muscles in each ear",
      "a cat uses its whiskers to determine if a space is too small to squeeze through",
      "a cats urine glows under a blacklight",
      "A cesium atom in an atomic clock beats over nine billion times a second.",
      "a chameleon's tongue is twice as long as its body",
      "a chameleons tongue is twice the length of its body",
      "A Chameleons tongue is twice the length of its body.",
      "A chameleon’s tongue is twice the length of its body.",
      "A chance of a woman having twins is increased after the age of 35. About 1 in 27 women will give birth to twins after this age. After 50 the chances of having twins is 1 in 9.",
      "a cheetahs top speed is 114kph (70mph)",
      "A chicken will lay bigger and stronger eggs if you change the lighting in such a way as to make them think a day is 28 hours long!",
      "A chimpanzee can learn to recognize itself in a mirror.",
      "a Chinese checkerboard has 121 holes",
      "A Citreon 2CV with an oil leak once travelled 500 miles through Italy after its gearbox was filled with bananas!",
      "A cockroach can live several weeks with its head cut off - it dies from starvation!",
      "A coffee tree yields about one pound of coffee in a year.",
      "A comet's tail always points away from the sun.",
      "A company in Taiwan makes dinnerware out of wheat, so you can eat your plate!",
      "A company in Taiwan makes dinnerware out of wheat, so you can eat your plate.",
      "A completely blind chameleon will still take on the colors of its environment.",
      "a connected bunch of bananas is called a hand and individual bananas are called fingers",
      "A cow gives nearly 200,000 glasses of milk in her lifetime.",
      "A cricket pitch is a rectangular area of the ground 22 yards (20 m) long and 10 ft (0 m) wide.",
      "A crocodile always grows new teeth to replace the old teeth!",
      "a crocodile can't move its tongue",
      "a crocodile can't stick out its tongue",
      "A crocodile's digestive juices are so strong that it can digest a steel nail.",
      "A cubic yard of air weighs about 2 pounds at sea level.",
      "a deck of cards should be shuffled at least 7 times before playing",
      "A dime has 118 ridges around the edge, a quarter has 119.",
      "a dolphins top speed is 60kmh (37mph)",
      "a dragonfly can fly at 40kph (25mph)",
      "A dragonfly has a lifespan of 24 hours.",
      "a duck can't walk without bobbing its head",
      "A female 'Rabbit'is called 'Doe'.",
      "a female ferret is called a jill",
      "A female whale is called a 'Cow'.",
      "A fetus develops fingerprints at eighteen weeks!",
      "A fire in Australia has been burning for more than 5,000 years!",
      "a flea can jump 350 times its body length",
      "a fly's recation time is 30 milliseconds",
      "a full moon is 9 times brighter than a half moon",
      "A full-grown bear can run as fast as a horse.",
      "A fully loaded supertanker traveling at normal speed takes a least twenty minutes to stop.",
      "a garfish has green bones",
      "a giraffe can clean its ears with its 21 inch tongue",
      "A giraffe can clean its ears with its 21-inch tongue!",
      "a giraffe can go longer without water than a camel",
      "A Giraffe has the same number of bones in its neck as a man.",
      "A group of chicken is called a flock.",
      "A group of crows can be called as 'Murder'.",
      'A group of dogs is called a "Kennel".',
      "A group of fish is called a school shoal draft run haul or catch.",
      "a group of foxes is called a skulk",
      "a group of frogs is called an army",
      "a group of geese is called a gaggle",
      "A group of geese on the ground is a gaggle, a group of geese in the air is a skein!",
      "a group of kangaroos is called a mob",
      "A group of officers is called a mess.",
      "a group of owls is called a parliament",
      "A group of rats is called as 'Colony'.",
      "a group of rhinos is called a crash",
      "a group of whales is called a pod",
      "a hard boiled eggs spin (uncooked or soft boiled don't)",
      "A hard working adult sweats up to 4 gallons per day.",
      "A hardboiled egg will spin. An uncooked or softboiled egg will not.",
      "A hedgehog's heart beats 300 times a minute on average!",
      "A hedgehog's heart beats 300 times a minute on average.",
      "A hippo can open its mouth wide enough to fit a 4 foot tall child inside!",
      "a hippopotamus can run faster than a man",
      "A honeybee's top speed is 24kph (15mph)",
      "a humming bird flaps its wings up to 90 times a second (5,400 times a minute)",
      "a hummingbird's heart beats at over a 1,000 times a minute",
      "A jellyfish is 95% water",
      "A jiffy is an actual unit of time for 1/100th of a second. Thus the saying, I will be there in a jiffy.",
      "A kangaroo cannot jump if its tail is off the ground.",
      "A killer whale’s heart beats 30 times a minute under water, 60 times a minute on the surface.",
      "a King Cobra is the biggest of all poisonous snakes and can grow to over 4 metres (13 feet) long",
      "A Koala Bear sleeps 22 hours of every day.",
      "A lady's heart beats faster than man's.",
      "A lightning bolt generates temperatures five times hotter than those found at the sun's surface!",
      "A lion's roar can be heard from more than five miles away.",
      "a lions feed once every 3 to 4 days",
      "a lobsters blood is colorless but when exposed to oxygen it turns blue",
      "A lump of pure gold the size of a matchbox can be flattened into a sheet the size of a tennis court!",
      "A lump of pure gold the size of a matchbox can be flattened into a sheet the size of a tennis court.",
      "a male baboon can kill a leopard",
      "A male baboon can kill a leopard.",
      "A male cat is called 'Tom' and a female is called as 'Queen'.",
      "A man gets robbed in London every 4.5 minutes! (and he is getting fed up of it)",
      "A man named Charles Osborne had the hiccups for 69 years!",
      "A man named Charles Osborne had the hiccups for approximately sixty-nine years.",
      "A man once sued his doctor because he survived his cancer longer than the doctor predicted.",
      "A marine catfish can taste with any part of its body.",
      "A mile on the Ocean and a mile on Land are not the same distance. Land (5280 feet) and Ocean (6080 feet).",
      "A million dollars' worth of $100 bills weighs only 22 pounds!",
      "A mole can dig a tunnel 300 feet long in just one night!",
      "a moth has no stomach",
      "a nanosecond is one billionth of a second",
      "A nest of young puppies is called as 'Liter'.",
      "a newborn kangaroo is about 1 inch in tall",
      "A one ounce milk chocolate bar has 6 mg of caffeine.",
      "A peanut is not a nut. It is a legume.",
      "A person infected with the SARS virus, has a 95-98% chance of recovery.",
      "a person produces enough saliva to fill 2 average size swimming pools during their lifetime",
      "A person swallows approximately 295 times while eating dinner.",
      "A person will burn 7% more calories if they walk on hard dirt compared to pavement.",
      "a person will die from total lack of sleep sooner than from starvation (Death can occur about 10 days without sleep while starvation takes a few weeks)",
      "a piece of paper cannot be folded more than 7 times",
      "a pip is one of the spots on die or domino",
      "A pipe 2 feet in diameter will allow four times more fluid to pass through it than a pipe 1 foot in diameter.",
      "a platypus can eat its weight in worms every day",
      "A polar bear's skin is black. Its fur is not white, but actually clear.",
      "A pound of potato chips costs 200 times more than a pound of potatoes.",
      "A pregnant goldfish is called a Twit.",
      "a pumpkin really is a fruit",
      "A quarter has 119 grooves on its edge, a dime has one less groove!",
      "a queen bee can lay up to 3,000 eggs in one day",
      "A queen bee uses her stinger only to sting another queen bee.",
      "A rainbow can only be seen in the morning or late afternoon.",
      "A raindrop is round but appears to be oval because gravitation pulls on the front of the raindrop as it is falling.",
      "A rat can fall from a five story building without injury.",
      "A rat can go without water longer than a camel can.",
      "a rat can tread water for 3 days",
      "A real estate agent’s rule of thumb:  To estimate what a house will sell for, ask the owner what its worth and subtract 10%.",
      "A recent study at Harvard has shown that eating chocolate can actually help you live longer!",
      "A roach can live up to nine days without its head.",
      "A rodent's teeth never stop growing.",
      "A Russian man who wore a beard during the time of Peter the Great had to pay a special tax.",
      "A Saudi Arabian woman can get a divorce if her husband doesn't give her coffee.",
      "a shark's teeth are literally as hard as steel",
      "a sharks top speed is 70kmh (44mph)",
      "a shrimp has 5 pairs of legs",
      "A shrimp's heart is in its head.",
      "A single 'RYE' plant can spread up to 400 miles of roots underground.",
      "A single cup of gasoline, when ignited, has the same explosive power as five sticks of dynamite.",
      "A small airplane can fly backwards.",
      "a snail can sleep for 3 years",
      "A snail can sleep for three years.",
      "A sneeze can travel as fast as 100 miles per hour.",
      "A sneeze travels out your mouth at over 100 m.p.h.!",
      "a soap bubble is 10,000 times thinner than the average human hair",
      "A solar eclipse occurred on July 22 2009 was the longest during the 21st century and it lasted a maximum of 6 minutes and 39 seconds.",
      "A species of earthworm in Australia grows up to 10 feet in length.",
      "a Sphygmomanometer measures blood pressure",
      "A spider's silk is stronger than steel.",
      "a squid has 10 tentacles",
      "a standard 747 jumbo jet has 420 seats",
      "A toaster uses almost half as much energy as a full-sized oven.",
      "A toothbrush within 6 feet of a toilet can get airborne bacteria from flushing.",
      "A tuna fish can swim 100 miles in a single day!",
      "A typical bed usually houses over 6 billion dust mites.",
      "A violin contains about 70 separate pieces of wood!",
      "A volcano has enough power to shoot ash as high as 50 km into the atmosphere.",
      "a whip makes a cracking sound because its tip moves faster than the speed of sound",
      "A woman's sense of smell is most sensitive during ovulation.",
      "a woodpecker can peck 20 times a second",
      "a woodpeckers tongue can wrap around its head twice",
      "A young fish can be called as 'Fry'.",
      "A young hen is called as 'Pullet'.",
      "A. P. J. Abdul Kalam born 15 October 1931 in Rameshwaram.",
      "A. S. Dileep Kumar was born 6 January 1966 and then converted to Islam in the year 1989 at the age of 23 and changed his name to 'Allah Rakha Rahman' (A.R.Rahman).",
      "ablutophobia is the fear of bathing",
      "About 20% of all volcanoes are under water.",
      "About 3000 years ago, most Egyptians died by the time they were 30!",
      "About 39,000 gallons of water are used to produce the average car!",
      "About 400 different kinds of microbes live on and in the human body.",
      "about 90% of the worlds population kisses",
      "About twenty-five% of the population sneeze when they are exposed to light.",
      "According to an age old custom, carrying a dead shrew in your pocket wards off rheumatism!",
      "According to an old English system of time units a moment is one and a half minutes.",
      "According to Gaming Law, casinos have to stock enough cash to cover all the chips on the 'floor'.",
      "According to legend, there’s a Superman in every episode of Seinfeld.",
      "according to manufacturer Spalding the average lifespan of an NBA basketball is 10,000 bounces",
      "According to scientific studies, a rat's performance in a maze can be improved by playing music written by Mozart.",
      "According to studies, men change their minds two to three times more often than women.",
      "according to the old English time system a moment is 1 and a half minutes",
      "achluophobiais the fear of the dark",
      "acorns are poisonous to humans (if eaten it can cause damage to your kidneys)",
      "acrophobia is the fear of heights",
      "Actor John Wayne made more than 200 movies.",
      "Actor Val Kilmer grew up on Roy Rogers' ranch.",
      "Actress Meryl Streep holds the record for the most Oscar nominated actress with a record of 13 nominations.",
      "African elephants only have 4 teeth",
      "African Grey Parrots have vocabularies of over 200 words",
      "after bananas a zoo gorilla's favorite food is celery",
      "After eating, a housefly regurgitates its food and then eats it again!",
      "after Hawaii, New York is the state surrounded by the most water",
      "after you've eaten it takes approximately 12 hours for food to entirely digest",
      "agoraphobia is the fear of wide open spaces",
      "aichmophobia is the fear of needles and pointed objects",
      "Airports that are at higher altitudes require a longer airstrip due to lower air density.",
      "akousticophobia is the fear of noises",
      "Al Capone died in prison from syphillis - despite being the first sufferer to be treated with antibiotics!",
      "Al Capone's business card said he was a used furniture dealer.",
      "Albert Einstein never knew how to drive a car",
      "Albert Einstein was offered the presidency of Israel in 1952, but he declined.",
      "Albert Einstien never wore any socks.",
      "Alexander the Great and Julius Caesar were both epileptic.",
      "Alfred Hitchcock didn't have a belly button.",
      "All babies are color blind when they are born.",
      "All clams start out as males; some decide to become females at some point in their lives.",
      "All coffee is grown within 1,000 miles of the equator.",
      "All Humans Are 99.9% Genetically Identical and 98.4% of human genes are the same as the genes of a chimpanzee.",
      "all hurricanes form over the sea and can last up to 10 days",
      "all insects have 6 legs",
      "All major league baseball umpires must wear black underwear while on the job!",
      "all of the clocks in the movie 'Pulp Fiction' are fixed to 4:20",
      "all of the cobble stones used to line the streets in New York were originally stones found in the hulls of Belgian ships ballast",
      "All of the Earth's continents are wider at the north than in the south - and nobody knows why.",
      "all owls lay white eggs",
      "all pilots on international flights identify themselves in English regardless of their country of origin",
      "All polar bears are left handed",
      "all snakes are carnivorous",
      "All species of beetles are edible.",
      "all the blinking in one day equates to having your eyes closed for 30 minutes",
      "All the gold ever mined could be molded into a cube 60 feet high and 60 feet wide.",
      "all the people on Earth could fit into a 1 km cube",
      "All the pet hamsters in the world are descended from a single wild golden Hamster found in Syria in 1930!",
      "all the planets in our solar system could fit inside Jupiter",
      "All the platinum ever mined would fit into an average-sized living-room!",
      "All the swans in England are property of the Queen.",
      "Allen Hill took the first wicket in test cricket when he dismissed Nat Thomson for ",
      "Almonds are a member of the peach family.",
      "almonds are members of the peach family",
      "Almost all varieties of breakfast cereals are made of grass.",
      "Aluminum used to be more valuable than gold!",
      "amathophobia is the fear of dust",
      "Among older men, vanilla is the most erotic smell.",
      "An 'aglet' is the plastic or metal tip of a shoelace.",
      "An adult giraffe's tongue is 17 inches long.",
      "An airplane mechanic invented Slinky while he was playing with engine parts and realized the possible secondary use for the springs.",
      "An albatross can sleep while it flies!",
      "An apple, potato, and onion all taste the same if you eat them with your nose plugged.",
      "an area of the Suns surface to the equivalent of a postage stamp would shine with the brightness of over 1,500,000 candles",
      "an arrow frog has enough poison to kill over 2,200 people",
      "an astronaut can be up to 2 inches taller returning from space (the cartilage disks in the spine expand in the absence of gravity)",
      "An average person eat 60000 pounds of food in his lifetime.",
      "An average person spent 24 years of his life in sleeping.",
      "an average person will spend 25 years asleep",
      "An average woman consume 6 lbs (72 kg). of lipstick in her lifetime.",
      "An eagle can attack, kill, and carry away an animal as large as a small deer.",
      "An earthquake on Dec. 16, 1811 caused parts of the Mississippi River to flow backwards!",
      "An earthquake on Dec. 16, 1811 caused parts of the Mississippi River to flow backwards.",
      "an egg contains every vitamin except vitamin C",
      "An egg will float if placed in water in which sugar has been added.",
      "An elephant trunk has no bone but 40,000 muscles.",
      "An elephant's tooth can weigh as much as 12 pounds.",
      "an elephant's trunk can hold over 5 litres of water",
      "an elephants ears are used to regulate body temperature",
      "An iceberg contains more heat than a lit match.",
      "an iguana can stay under water for 28 minutes",
      "an individual blood cell takes about 60 seconds to make a complete circuit of the body",
      "an octopus pupil is rectangular",
      "an office desk has 400 times more bacteria than a toilet",
      "An olive tree can live up to 1,500 years!",
      "an ostrich's eye is bigger than its brain",
      "An ostrich's eye is bigger than its brain.",
      "an ostriches can outrun a horse",
      "an ostriches life span is 40-45 years",
      "An ounce of platinum can be stretched 10,000 feet.",
      "Ancient Egyptians slept on pillows made of stone!",
      "Ancient Egyptians slept on pillows made of stone.",
      "Ancient Romans at one time used human urine as an ingredient in their toothpaste.",
      "and the viewers were never told!",
      "Animals will not eat another animal that has been hit by a lightning strike!",
      "Annually, the amount of garbage that is dumped in the world's oceans is three times the weight of fish that is caught from the oceans.",
      "Another name for a Microsoft Windows tutorial is 'Crash Course'!",
      "Antarctica is 98% ice and 2% barren rock",
      "Antarctica is the only land on our planet that is not owned by any country.",
      "Anteaters prefer termites to ants.",
      "ants can lift 50 times their own weight",
      "ants don't like baby powder (talcum powder)",
      "Ants don’t sleep.",
      "Any modern jet is capable of breaking the sound barrier.",
      "Any space vehicle must move at a rate of 7 miles per second in order to escape the earth's gravitational pull.",
      "Aoccdrnig to a rscheearch procejt at Cmabrigde Uinervtisy, it deosnt mttaer waht oredr the ltteers in a wrod are, the olny iprmoatnt tihng is taht the frist and lsat ltteer be in the rghit pclae. Tihs is bcuseae the huamn mnid deos not raed ervey lteter b",
      "Apple company was founded by Steve Jobs Steve Wozniak and Ronald Wayne on April 1 197",
      "Apple seeds are poisonous!",
      "Apples are 25% air.",
      "Apples are actually part of the rose family.",
      "apples are more effective at waking you up in the morning than coffee",
      "Apples are more efficient than caffeine in keeping people awake in the morning.",
      "Approximately $25 million is spent each year on lap dances in Las Vegas.",
      "Approximately 115 tons of ocean salt spray enters the earth's atmosphere each second.",
      "Approximately 25,000 workers died during the building of the Panama Canal, and approximately 20,000 of them contracted malaria and yellow fever.",
      "Approximately 70% of the earth is covered by water. Only 1% of this water is drinkable.",
      "Approximately one-third of the population can't snap their fingers!",
      "arachibutyrophobia is fear of peanut butter sticking to the roof of your mouth",
      "Arctic ice is rapidly disappearing and the region may have its first completely ice-free summer by 2040 or earlier. Polar bears and indigenous cultures are already suffering from the sea-ice loss.",
      "Area wise India is the 7th largest country in the world.",
      "Armadillos can get leprosy.",
      "armadillos can walk underwater",
      "armadillos have 4 babies at a time and are all the same sex",
      "Arnold Schwarzenegger’s voice, in the movie 'Hercules', was dubbed.",
      "Arthur Conan Doyle, author of the Sherlock Holmes stories, was an ophthalmologist by profession!",
      "artificial Christmas trees have outsold real ones every year since 1991",
      "as a world commodity coffee is second only to oil",
      "Astronauts cannot burp in space.",
      "Astronauts get taller when they are in space.",
      "At  one 'feeding', a mosquito can absorb one and a half times its own weight in blood.",
      "At 120 miles per hour, a Formula One car generates so much downforce that it can drive upside down on the roof of a tunnel.",
      "At 188 decibels, the whistle of the blue whale is the loudest sound produced by any animal",
      "At age 18, the Queen of England was a mechanic for the British Military.",
      "At age 70, more than 70% of men are still potent!",
      "at birth dalmations are always white",
      "At birth, a panda bear is smaller than a mouse.",
      "At horse race tracks, the favorite wins fewer than 30% of the time!",
      "At room temperature, the average air molecule travels at the speed of a rifle bullet.",
      "Atilla the hun was a dwarf!",
      "Attics were invented in Attica.",
      "atychiphobia is the fear of failure",
      "August has the highest percentage of births",
      "Australia has the largest sheep population",
      "Australia is the only country that is also a continent",
      "Australia was originally called New Holland",
      "Australia's Great Barrier Reef is 1,250 miles long!",
      "Austria was the first country to use postcards.",
      "Average distance from the Earth to the Sun: 93020000 miles (149669180 km)",
      "Avocados are poisonous to birds.",
      "Avocados have more protein than any other fruit.",
      "avocados have the most calories of any other fruit",
      "Babe Ruth wore a cabbage leaf under his cap to keep him cool! He changed it every 2 innings!",
      "Babe Ruth wore No. 3 because he batted third.",
      "Babies are born without knee caps.",
      "Babies start dreaming even before they're born.",
      "Babies that are breastfed are more likely to be slimmer as adults than those that are not breastfed.",
      "Babies who wear disposable diapers are five times more likely to develop diaper rash than those that wear cotton diapers.",
      "Babies' eyes do not produce tears until the baby is approximately six to eight weeks old.",
      "Baby beavers are called kittens.",
      "baby rattlesnakes are born in August and September",
      "Baby robins eat 14 feet of earthworms every day!",
      "Baby robins eat 14 feet of earthworms every day.",
      "Baby whales grow at an average rate of 10lbs per hour!",
      "Bacteria that cause tooth decay, acne, tuberculosis, and leprosy can be cured with cashews.",
      "Bali has the worlds largest variety of flora",
      "Balsa wood is classified as a hard wood!",
      "Bamboo plants can grow up to 36 inches in a day.",
      "banana plants are the largest plants without a woody stem (they belong to the same family as lilies, orchids and palms)",
      "banana plants can grow as high as 6 meters (20 feet) tall",
      "bananas are a good source of vitamin C, potassium and fiber",
      "Bananas aren’t fruit! They are a type of herb.",
      "Bananas contain a natural chemical which can make a person happy. This same chemical is also found in Prozac.",
      "bananas contain no fat, cholesterol or sodium",
      "bananas grow pointing upwards.",
      "Banging your head against a wall uses 150 calories an hour.",
      "Bank robber John Dillinger played professional baseball.",
      "Barbie's full name is Barbara Millicent Roberts.",
      "Barbie's full name is Barbara Millicent Roberts.",
      "Basketball great Wilt Chamberlain never fouled out of a game.",
      "Baskin Robbins once made ketchup ice cream.",
      "Bats always turn left when exiting a cave!",
      "Bats always turn left when exiting a cave.",
      "bats are the only mammals that fly",
      "Beavers can swim half a mile underwater on one gulp of air.",
      "Beavers have orange teeth!",
      "Because heat expands the metal, the Eiffel Tower always leans away from the sun.",
      "Because metal was scarce; the Oscars given out during World War II were made of plaster.",
      "Beelzebub is Hebrew for 'Lord of the Flies'.",
      "bees and house flies flap their wings 200 times a second",
      "bees can see ultraviolet light",
      "bees have 4 wings",
      "before 1850 golf balls were made of leather and were stuffed with feathers",
      "before beginning his movie career Keanu Reeves managed a pasta shop in Toronto Canada",
      "Betsy Ross was born with a fully formed set of teeth.",
      "between 1931 and 1969 Walt Disney was awarded 35 Oscars",
      "Bill Gates began programming computers at the of age 13",
      "Bill Gates designed a traffic control system for Seattle when he was only 15!",
      "Bill Gates' house was designed using a Macintosh computer.",
      "Billy goats urinate on their own heads to smell more attractive to females.",
      "birds need gravity to swallow",
      "Black bears are not always black. They can be brown, cinnamon, yellow, and sometimes white.",
      "black on yellow are the 2 colors with the strongest impact",
      "Black Whales are born white.",
      "Blaise Pascal worked on the calculator for three years between 1642 and 1645 called as 'Pascaline'.",
      "blonde beards grow faster than darker beards",
      "Blood in animals and sap in plants is composed mainly of water.",
      "blue and white are the most common school colors",
      "Blue eyes are the most sensitive to light, dark brown the least sensitive.",
      "Blue Peter pet, Petra the mongrel puppy, died two days after being introduced. A replacement was found",
      "blueberries are very high in antioxidants",
      "Blueberry juice boosts memory.",
      "Bluebirds cannot see the color blue.",
      "Bob Hope and Billy Joel were both once boxers.",
      "bottle nosed whales can dive to a depth of 915 metres (3,000feet) in 2 minutes",
      "Boys who have unusual first names are more likely to have mental problems than boys with conventional names. Girls don't seem to have this problem.",
      "Brad Pitt has been smoking since the sixth grade!",
      "Brazil accounts for 1/3 of the world's coffee production",
      "Brazil got its name from the Brazilian nut (not the other way around)",
      "Brazil is named after a tree",
      "Brazil is the only country to appear in every FIFA world Cup. (19 times)",
      "Britain was the first country to use postage stamps",
      "brontology is the study of thunder",
      "brontophobia is the fear of thunderstorms",
      "Bruce lee (27-Nov-1940 to 20-July-1973) was the founder of the Jeet Kune Do martial arts movement.",
      "Buckingham Palace has over 600 rooms",
      "Budget: $300000000",
      "Budweiser beer is named after a town in Czechoslovakia.",
      "bull's can run faster uphill than down",
      "bulletproof vests, fire escapes, windshield wipers, and laser printers were all all invented by women",
      "Bulls are colorblind, therefore will usually charge at a matador's waving cape no matter what color it is -- be it red or neon yellow!",
      'Burj Khalifa (Arabic:"Khalifa Tower") known as Burj Dubai prior to its inauguration is a skyscraper in Dubai United Arab Emirates and the tallest man-made structure ever built at 828 m (2717 ft).',
      "Burt Reynolds is a Cherokee Indian.",
      "Business.com is currently the most expensive domain name sold for $7.5 million.",
      "butterflies taste with their back feet",
      "Butterflies taste with their feet.",
      "Butterflies “smell” with their antennae and “taste” with their feet.",
      "Buttermilk does not contain any butter.",
      "By 3,000 B.C. there were at least six different types of beer in Egypt.",
      "by age 60 most people would have lost half of their taste buds",
      "By feeding hens certain dyes they can be made to lay eggs with multi-colored yolks.",
      "By partially filling saucers with vinegar and distributing the saucers around a room, you can eliminate odors.",
      "By raising your legs slowly and laying on your back, you can't sink in quicksand.",
      "By recycling just one glass bottle, the amount of energy that is being saved is enough to light a 100 watt bulb for four hours.",
      "By the age of 17 Bill Gates had sold his first computer program a time-tabling system for his high school for $420",
      "By the age of 60, most people have lost 50% of their taste buds.",
      "C3PO is the first character to speak in Star Wars.",
      "cabbage is 91% water",
      "California has issued at least 6 drivers licenses to people named Jesus Christ.",
      "camel's milk doesn't curdle",
      "camels are born without humps",
      'Camels are called "ships of the desert"because of the way they move not because of their transport capabilities.',
      "camels can drink 94 litres (25 gallons) of water in less than 3 minutes",
      "camels have 3 eyelids to protect themselves from blowing sand",
      "Camels have three eyelids to protect themselves from blowing sand!",
      "Canada has more doughnut shops per capita than any other country",
      "Canada has more lakes than any other country",
      "Canada is an Indian word meaning 'Big Village'.",
      "Canada's new flag, with its maple leaf design, was unfurled in 1965 in Ottawa!",
      "Canola oil is actually rapeseed oil but the name was changed for marketing reasons!",
      "Car accidents rise 10% during the first week of daylight savings time.",
      "Car airbags kill 1 person for every 22 lives that they save.",
      "carrots contain 0% fat",
      "cars were first started with ignition keys in 1949",
      "Cashew nut shells contain oil that is extremely irritating to human skin.",
      "Castor oil is used as a lubricant in jet planes.",
      "Cat urine glows under a black-light!",
      "caterpillars have over 2,000 muscles",
      "Caterpillars have over 2000 muscles.",
      "catfish have over 100,000 taste buds",
      "Catgut comes from sheep not cats.",
      "catoptrophobia is the fear of mirrors",
      "cats can jump up to 7 times their tail length",
      "cats can't move their jaw sideways",
      "Cats cannot taste sweet things.",
      "cats have a peripheral vision of 285 degrees",
      "Cats have a peripheral vision of 285 degrees.",
      "cats have over 100 vocal chords",
      "Cats make over 100 different vocal sounds; dogs can make about ten.",
      "Cats sleep 16 to 18 hours per day.",
      "cats spend 66% of their life asleep",
      "Cats’ urine glows under a black light.",
      "Cattle are the only mammals that pee backwards.",
      "Cellophane is not made of plastic. It is made from a plant fiber, cellulose, which has been shredded and aged.",
      "Chained dogs are 3 times more likely to bite than unchained dogs.",
      "chalk is made from tiny plankton fossils",
      "chameleons can move their eyes in two directions at the same time",
      "Che Guevara suffered from asthma!",
      "Check your map!  The Pacific entrance of the Panama Canal is farther East than the Atlantic entrance.",
      "Check your map! Virginia extends farther west than West Virginia.",
      "Cheerios cereal was originally called Cheerioats",
      "cheetahs can accelerate from 0 to 70 km/h (43mp/h) in 3 seconds",
      "Cheetahs were raced at Romford greyhound stadium in 1937!",
      "Chennai is now called the Detroit of India due to its automobile industry producing over 40% of the country's auto parts and vehicles.",
      "Chevy Chase's real first name is Cornelius",
      "Chewing gum while peeling onions will keep you from crying!",
      "Chewing on gum while cutting onions can help a person from producing tears.",
      "chicken drumsticks contain the least amount of meat on a chicken",
      "Children are more allergic to cockroaches than they are to cats!",
      "Children are poisoned most frequently by eating harmful plants.",
      "Children grow faster in the springtime than any other season during the year.",
      "Children laugh about 400 times a day, while adults laugh on average only 15 times a day.",
      "China is the source of 70% of the worlds pirated goods.",
      "China manufacturers 70% of the worlds toys",
      "chocolate is the number 1 food craved by women",
      "chocolate manufacturers use 40% of the world's almonds",
      "Chop Suey was invented in New York!",
      "Chop-suey is not a native Chinese dish, it was created in California by Chinese immigrants.",
      "Christmas trees originated from Germany",
      "Chrysler built B-29's that bombed Japan, Mitsubishi built Zeros that tried to shoot them down. Both companies now build cars in a joint plant called Diamond Star.",
      "Cinematon (1978) is a 152-hour long experimental film by French director Gerard Courant. It is considered to be the longest film ever released.",
      "City dwellers have longer, thicker, denser nose hairs than country folks do.",
      "Clinophobia is the fear of beds!",
      "clinophobia is the fear of going to bed",
      "Clocks made before 1660 had only one hand - an hour hand.",
      "clothes dried outside smell better because of a process called photolysis (sunlight breaks down compounds that cause odor)",
      "clouds fly higher during the day than the night",
      "Club Direct, a travel insurance company in Britain, provides insurance plans for protection from falling coconuts.",
      "Coca Cola launched its 3rd product Sprite in 1961",
      "Coca Cola was founded by Joseph A Biedenharn",
      "Coca-Cola originally contained cocaine",
      "Coca-Cola was the first soft drink to be consumed in outer space.",
      "Coca-Cola's 'Super Pure' Dasani bottled water is just filtered tap water!",
      "Coconuts kill more people in the world than sharks do. Approximately 150 people are killed each year by coconuts.",
      "coconuts kill over 150 people each year (more than sharks)",
      "Coffee beans aren't beans - they're fruit pits.",
      "coffee is generally roasted between 204 - 218C (400 - 425F) (the longer the beans are roasted the darker the roast)",
      "coffee is grown commercially in over 45 countries around the world",
      "Coffee is the largest item bought and sold next to Petrol.",
      "coffee is the most popular beverage worldwide with over 400 billion cups consumed each year",
      "coffee trees produce its first full crop after 5 years old",
      "Cold water weighs more than hot water.",
      'Colgate faced a big obstacle marketing toothpaste in Spanish speaking countries. Colgate translates into the command "go hang yourself."',
      "Colgate's first toothpaste came in a jar.",
      "Connecticut and Rhode Island never ratified the 18th Amendment (Prohibition).",
      "Construction of the Taj Mahal began in 1632 one year after her death of his wife Mumtaz.",
      "Contrary to popular belief, dogs do not only sweat by salivating. They also sweat through the poors on their feet.",
      "Contrary to popular belief, hair does not grow back darker and thicker after it has been shaved.",
      "Contrary to popular belief, lightning travels from the ground upwards not from the sky downwards.",
      "Contrary to popular belief, London Broil is not a cut of beef but rather a method of cooking.",
      "Contrary to popular belief, opossums, squirrels, chipmunks, and mice do not carry rabies.",
      "Contrary to popular belief, putting sugar in a car's gas tank will NOT ruin its engine.",
      "Contrary to popular belief, the first ironclad warships were built by Korea in the 16th century.",
      "Contrary to popular belief, there are almost no Buddhists in India, nor have there been for about a thousand years.",
      "Contrary to popular beliefs, chocolate does not cause acne.",
      "cooking or freezing does not reduce the heat (spiciness) of a chile pepper",
      "Cow is a Japanese brand of shaving foam.",
      "cows don't have upper front teeth",
      "Cranberries are sorted for ripeness by bouncing them; a fully ripened cranberry can be dribbled like a basketball.",
      "Crayola is a French word that means 'Oily chalk.",
      "Crocodile babies don't have sex chromosomes; the temperature at which the egg develops determines gender.",
      "crocodiles are colour blind",
      "Crocodiles are colour blind.",
      "crocodiles are responsible for over a 1,000 deaths each year by the Banks of the Nile river",
      "crocodiles continually grow new sets of teeth to replace old ones",
      "crocodiles never outgrow their enclosure",
      "crocodiles swallow rocks to help them dive deeper",
      "Crocodiles swallow stones to help them dive deeper.",
      "Crushed cockroaches can be applied to a stinging wound to help relieve the pain.",
      "cucumbers are 96% water.",
      "Dandelion root can be roasted and ground as a coffee substitute.",
      "dark green lettuce leaves are more nutritious than lighter ones",
      "dark roasted coffee beans contain less caffeine than medium roasted ones (the longer a coffee is roasted the more caffeine is burns off)",
      "Dating back to the 1600's, thermometers were filled with Brandy instead of mercury.",
      "Deep Breathing gives you health benefits similar to aerobics.",
      "deers don't like hay",
      "dendrophobia is the fear of trees",
      'Dennis Ritchie "offically"created the C programming language while working at Bell labs.',
      "Despite the hump, a camel's spine is straight.",
      "diamonds are the hardest natural substance",
      "diamonds are the hardest substance known to man",
      "Diamonds mined in Brazil are harder than those found in Africa.",
      "diamonds mined in Brazil are much harder than those found in Africa",
      "Diet Coke was introduced in 1982",
      "Diet Pepsi was originally called Patio Diet Cola.",
      "dinosaurs lived on Earth for over 165 million years before they became extinct",
      "Dirty snow melts faster than clean.",
      "dirty snow melts quicker than clean snow",
      "Discovery channel was started on June 17 198",
      "Disneyland opened in 1955",
      "DNA stands for Deoxyribonucleicacid",
      "Dogs and cats consume over $11 billion worth of pet food a year!",
      "Dogs and cats, like humans, are either right or left handed... or is that paws?!",
      "Dogs can hear sounds that you cant!",
      "dogs sweat through the pads on their feet",
      "dolphin's can detect underwater sounds from 24 km (15 miles) away",
      "dolphins can hear underwater sounds from 24km (15miles) away",
      "dolphins can kills sharks by ramming them with their snout",
      "Dolphins nap with one eye open.",
      "Dolphins sleep with one eye open!",
      "domestic cats dislike citrus scents",
      "Domestic cats hate lemons or other citrus scents.",
      "Donkeys are commonly used by the Iraqi Military to launch rockets!",
      "Donkeys kill more people annually than plane crashes.",
      "Douglas Engelbart (invented computer mouse) was awarded the 1997 Lemelson-MIT Prize of $500000 the world's largest single prize for invention and innovation.",
      "Dragonflies can travel up to 60 mph.",
      "dragonflies have 6 legs but can't walk",
      "Dragonflies have six legs but cannot walk!",
      "Dragonfly eye contains 30000 lenses.",
      "draughts (checkers) is older than chess",
      "Dreamt is the only English word that ends in the letters mt",
      "dreamt is the only word that ends in mt",
      "Drew Carey once worked at a Denny's.",
      "Drivers kill more deer than hunters.",
      "dry ice transforms directly from being a solid to a gas",
      "Ducks will only lay eggs early in the morning.",
      "due to gravitational effects you weigh is slightly less when the moon is directly overhead",
      "Due to gravitational effects, you weigh slightly less when the moon is directly overhead.",
      "DUEL (1971) was the first feature film directed by Steven Spielberg and was written by Richard Matheson based on his own short story.",
      "Dueling is legal in Paraguay, as long as both parties are registered blood donors.",
      "Duracell, the battery-maker, built parts of its new international headquarters using materials from its own waste.",
      "During a typical human life span, the human heart will beat approximately 2.5 billion times.",
      "During his lifetime, artist Vincent Van Gogh only sold one of his paintings.",
      "During his lifetime, Herman Melville's Moby Dick sold only 50 copies.",
      "During his or her lifetime, the average human will grow 590 miles of hair.",
      "During menstruation, the sensitivity of a woman's middle finger is reduced.",
      "During the 1600's, boys and girls in England wore dresses until they were about seven years old.",
      "During the Gold Rush in 1849, some people paid as much as $100 for a glass of water!",
      "During WWII, because a lot of players were called to duty, the Pittsburgh Steelers and Philadelphia Eagles combined to become The Steagles.",
      "During your lifetime, you'll eat about 60,000 pounds of food, that's the weight of about 6 elephants!",
      "During your lifetime, you'll eat about 60,000 pounds of food, that's the weight of about 6 elephants.",
      "DVDs are physically the same size as a CDs but can store 13 times more data",
      "Each 5 m.p.h. you drive over 60 m.p.h. is like paying an additional $.10 a gallon for gas!",
      "Each day is longer than the previous on by 0.00000002 seconds which is 13 seconds each century!",
      "Each day, more than $40 Trillion Dollars changes hands worldwide.",
      "Each day, up to 150 species of life become extinct.",
      "Each nostril of a human being register smell in a different way. Smells that are made from the right nostril are more pleasant than the left.",
      "each red blood cell lives an average of 4 months and travels between the lungs and other tissue 75,000 times before returning to bone marrow to die",
      "each time you see a full moon you always see the same side",
      "each year there is one ton of cement poured for each man, woman, and child",
      "Each year, the average family uses about 18,000 gallons of water just to do its laundry!",
      "Eagles mate while airborne.",
      "Early Romans used to use porcupine quills as toothpicks.",
      "Ears of corn always have an even number of rows of kernels.",
      "Earth is the only planet not named after a god",
      "Earth's Circumference between the North and South Poles: 248582 miles (40008 km)",
      "Eddie Cochran's last recording before he died was Three Steps to Heaven!",
      "Einstein slept 10 hours a night",
      "Electricity doesn't move through a wire but through a field around the wire.",
      "Elephants are the only animals that can't jump.",
      "elephants can run up to 40kmh (25mph)",
      "elephants communicate in sound waves below the frequency that humans can hear",
      "elephants sleep between 4 - 5 hours in 24 period",
      "Elephants, lions, and camels roamed Alaska 12,000 years ago.",
      "EMI awards stands for 'Electrical and Musical Instruments'",
      "Emile Berliner invented the microphone in 187",
      "employees are more likely to book holidays off work on a Monday that any other week day",
      "employees of the Vatican pay no income tax",
      "Emus and kangaroos cannot walk backwards.",
      "emus can't walk backwards",
      "Energy is being wasted if a toaster is left plugged in after use.",
      "English novelist Arnold Bennet drank a glass of water in a Paris Hotel to prove it was safe. He died two months later of Typhoid!",
      "Enrico Caruso and Roy Orbison were the only tenors this century capable of hitting e over high c!",
      "Ernest Vincent Wright wrote a novel, Gadsby, which contains over 50,000 words -- none of them with the letter E!",
      "Eskimo ice cream is neither icy, or creamy!",
      "Europe is the only continent without a desert.",
      "Even a small amount of alcohol placed on a scorpion will make it go crazy and sting itself to death.",
      "Even Antarctica has an area code. It’s 672.",
      "Even though lionesses make the hunt they eat the prey only after the males have had their full. The cubs eat after the lionesses.",
      "Everton FC used to be called St Domingo's FC!",
      "Every Alaskan citizen over the age of 6 months receives an oil dividend check of about $1000 per year!",
      "Every day 400000 babies are born and 140000 people die.",
      "Every day, the average person swallows about a quart of mucous.",
      "Every hour one billion cells in the body must be replaced.",
      "every living thing on the Earth contains carbon",
      "every single possible 3 character .com domain has been registered",
      "every square inch of the human body has an average of 32 million bacteria on it",
      "Every three seconds, a new baby is born.",
      "Every time you lick a stamp, you're consuming 1/10 of a calorie!",
      "Every workday, 6.7 million people commute to Manhattan!",
      "every year over 98% of atoms in your body are replaced",
      "every year the sun loses 360 million tons",
      "Every year, Alaska has about 5,000 earthquakes.",
      "everyday is a holiday somewhere in the world",
      "everyone has a unique tongue print",
      "Expansion of NASA is National Aeronautics and Space Administration and was established on July 29 195",
      "Extremely high pressured water can easily cut through a steel beam.",
      "Famous billionaire Howard Hughes stored his own urine in large bottles.",
      'Famous lyricist "Vairamuthu"was born on 13-July-1953. He received the National Award 5 times in his career so far.',
      "Farmers in England are required by law to provide their pigs with toys!",
      "Fathers tend to determine the height of their child mothers their weight.",
      "Fear of 'heights' is called as 'Acrophobia'.",
      "Fear of blood is called as 'Hemaphobia'.",
      "February 1865 is the only month in recorded history to not have a full moon.",
      "Female canaries cannot sing.",
      "female condors lays a single egg once every 2 years",
      "Females learn to talk earlier, use sentences earlier, and learn to read more quickly than males.",
      "ferrets sleep between 18 - 20 hours a day",
      "FIFA 2006 World Cup: Italy won their fourth world crown in Germany beating France on penalties in Berlin on 09 July 200",
      "Fifteen people are known to have been crushed to death tilting vending machines towards them in the hope of a free can of soda.",
      "Fine-grained volcanic ash can be found as an ingredient in some toothpastes.",
      "Fingernails grow fastest on the hand you favor.",
      "Fingernails grow nearly 4 times faster than toenails!",
      "Finland has the largest number of islands in the world (over 179,550)",
      "fire usually moves faster uphill than downhill",
      "First-cousin marriages are legal in Utah, so long as both parties are 65 or older!",
      "Fish have been on the earth for more than 450 million years.",
      "flamingoes can live up to 80 years old",
      "flamingos can only eat when their head are upside down",
      "Flamingos pee on their legs to cool themselves off.",
      "fleas can accelerate 50 times faster than a space shuttle",
      "flies can react to an object it sees and change direction in less than 30 milliseconds",
      "Florida has more tornados per square mile than any other state.",
      "Flu shots only work about 70% of the time.",
      "flushable toilets were in use in ancient Rome",
      "Flying from London to New York by Concord due to the time zones crossed you can arrive 2 hours before you leave.",
      "flys always launch backwards for a quick getaway",
      "Food can only be tasted if it is mixed with saliva.",
      "For beer commercials, they add liquid detergent to the beer to make it foam more.",
      "For every 'normal' webpage, there are five porn pages.",
      "For every gallon of sea water, you get more than a quarter pound of salt.",
      "for every human there are 200 million insects",
      "For people that are lactose intolerant, chocolate aids in helping milk digest easier.",
      "Forensic scientists can determine a person's sex, age, and race by examining a single strand of hair.",
      "Forest fires move faster uphill than downhill.",
      "Franklin Mars invented the Snickers Bar in 1930",
      "french fries are originally from Belgium",
      "French was the official language of England for over 600 years.",
      "fresh apples float because they contain 25% air",
      "frogs can't swallow with their eyes open",
      "frogs don't usually swallow water (they absorb most of the moisture they need through their skin)",
      "Frogs sometimes eat enough fireflies that they themselves glow.",
      "From a complete stop, a human is capable of outrunning a Formula One Racecar for about 30 feet!",
      "from space the brightest man made place is Las Vegas",
      "From the age of thirty, humans gradually begin to shrink in size.",
      "Frozen lobsters can come back to life when thawed!",
      "Gardening is said to be one of the best exercises for maintaining healthy bones.",
      "gatophobia is the fear of cats",
      "George Washington and Thomas Jefferson grew marijuana on their plantations!",
      "German chemists made a replica of a trophy the size of one molecule.",
      "Germany and Brazil are the two countries with most appearances in a World Cup final. (7 times)",
      "Germany borders 9 other countries",
      "Giant Panda Bears give birth to a 4 ounce Baby Panda!",
      "giant tortoises can live in captivity longer than any other animal",
      "giraffes and rats can last longer without water than camels",
      "giraffes can't cough",
      "giraffes can't swim",
      "giraffes has the highest blood pressure of any animal",
      "giraffes have no vocal cords",
      "Girls have more tastebuds than boys.",
      "Given the opportunity, deer will chew gum and marijuana.",
      "Gloucestershire airport in England used to blast Tina Turner songs on the runways to scare birds away.",
      "Gmail was launched as an invitation-only beta release on April 1 2004 and it became available to the general public on February 7 200",
      "Goat's milk is used more widely throughout the world than cow's milk.",
      "Goats do not have upper front teeth.",
      "Gold leaf is attached to paper or plaster with egg whites, the same now as in ancient times!",
      "Gold never erodes.",
      "goldfish can see both infrared and ultraviolet light",
      "Goldfish cant close their eyes.",
      "Goldfish lose their color if they are kept in dim light or are placed in a body of running water, such as a stream.",
      "Goldfish remember better in cold water than warm water.",
      "Goodyear Rubber Company researched and concluded that shoes wear out faster on the right foot than the left.",
      "Google consists of over 450000 servers racked up in clusters located in data centers around the world.",
      "Google's name is a play on the word googol which refers to the number 1 followed by one hundred zeroes.",
      "Google.com - After entering search keyword On clicking 'I'm feeling lucky' button it will open the first result's website directly.",
      "gorillas can't swim",
      "gorillas sleep 14 hours a day",
      "Grapes explode when you put them in the microwave.",
      "grasshoppers have white blood",
      "green tea has 50% more vitamin C than black tea",
      "Grenades were invented in China over 1,000 years ago.",
      "greyhounds can reach speeds of up to 67kph (42mph)",
      "Greyhounds have the best eyesight of any breed of dog.",
      "gunpowder is formed by mixing charcoal, saltpetre and sulphur",
      "half of all crimes are committed by people under the age of 18",
      "Half of all identity thieves are either relatives, friends, or neighbors of their victims.",
      "Halifax, Nova Scotia, Canada has the most bars per capita than anywhere else in the world.",
      "Halle Berry’s stunt double, in the movie “Catwoman”, is a man.",
      "Halley's comet passes the Earth every 76 years (the next time it will return will be 2062)",
      "Harrison Ford has a species of spider named after him!",
      "Harrods have three private wells to supply their water!",
      "Hawaii was originally called the Sandwich Islands",
      "Height of the Great pyramid of Giza is 1375 metres (4522 ft).",
      "Heineken beer is designed to 'foam' for exactly five minutes.",
      "heliophobia is the fear of sunlight",
      "helminthophobia is the fear of worms",
      "Henry Ford produced the model T only in black because the black paint available at the time was the fastest to dry.",
      "Henry Ford was Charles Lindbergh's first passenger in the Spirit of St. Louis.",
      "Henry Ford, father of the Automobile, is also father of the charcoal briquette.",
      "herpetophobia is the fear of reptiles",
      "hiccups usually lasts for 5 minutes",
      "Highest Temperature Recorded: 138°F - Al Aziziyah Libya September 13 1922 (57°C)",
      "Hilton was the first international hotel chain",
      "hippophobia is the fear of horses",
      "hippopotamuses are born under water",
      "hippopotamuses have killed more people in Africa than any other animal",
      "hippopotamuses have skin 3.8cm (1.5in) thick",
      'Hiroshima bombed by "Col. Paul Tibbets"on August 6 1945 at 8:15 A.M. local time.',
      "honey bees kill more people each year than snakes",
      "honey enters your blood stream within 20 minutes of being eaten",
      "honey is the only natural food which never spoils",
      "Honey is used sometimes for antifreeze mixtures and in the center of golf balls.",
      "Honeybees have a type of hair on their eyes!",
      "Hong Kong has more Rolls Royces per person than anywhere else in the world.",
      "horses have 18 more bones than humans",
      "horses sleep standing up",
      "Houdini was the first man to fly a plane solo in Australia.",
      "house cats have 18 claws",
      "household dust is made of dead skin cells",
      "How does a shark find fish?  It can hear their hearts beating.",
      "However they cannot sub if a player has been sent off with a red card.",
      "Human birth control pills work on gorillas.",
      "Human teeth are almost as hard as rocks!",
      "human thigh bones are stronger than concrete",
      "humans are the only primates that don't have pigment in the palms of their hands",
      "Humans blink over 10,000,000 times a year!",
      "humans shed and regrow outer skin cells every 27 days (almost 1,000 new skins in a lifetime)",
      "hummingbirds are the only bird that can fly backwards",
      "Hummingbirds can weigh less than a penny!",
      "Hummingbirds can't walk.",
      "hydrogen is the most abundant element in the Universe (75%)",
      "Hyenas regularly eat the feces of other animals!",
      "iatrophobia is the fear of doctors",
      "ice skating rinks always go counter clock wise (for the majority of people that are right handed needing to hang onto the rail)",
      "Iceland consumes more Coca Cola per capita than any other country",
      "Iceland has no railway system or army!",
      "Iceland was the first country to legalise abortion in 1935",
      "Icelandic phone books are listed by first names (not surnames)",
      "ichthyophobia is the fear of fish",
      "ICICI Bank (formerly Industrial Credit and Investment Corporation of India) was incorporated at the initiative of World Bank in 195",
      "Identical twins do not have identical fingerprints.",
      "Identify a fake:  The second hand on an authentic Rolex watch doesn't tick, it moves smoothly.",
      "If a car is travelling at 55 miles per hour it will travel 56 feet before the driver can shift his foot from the accelerator to the brake.",
      "If a Lobster loses an eye, it will grow another one.",
      "If a new player takes more than 3 minutes to be ready to face or be ready for his partner to face the next delivery after the previous batsman was ruled out then the new player is given timed-out in cricket.",
      "If a surgeon in Ancient Egypt lost a patient while performing an operation, his hands were cut off.",
      "If China imported just 10% of it's rice needs- the price on the world market would increase by 80%.",
      "If it isn’t moving a frog can’t see it. If the frog can’t see it, he won’t eat it.",
      "If Manhattan had the same population density as Alaska, there would only be 15 people living there.",
      "If the chemical sodium is dropped into water it will immediately and violently explode.",
      "If the population of China walked past you in single file, the line would never end because of the rate of reproduction.",
      "If Wal-Mart was classified as a country, it would be the 24th most productive country in the world.",
      "If water in our body is reduced by 10% we will die.",
      "if you add up all the numbers from 1 to 100 consecutively (1 + 2 + 3...) it totals 5050",
      "If you are bitten by a poisonous snake, and fail to receive medical attention, you still have a 50% chance of survival.",
      "If you are locked in a completely sealed room, you will die of carbon dioxide poisoning first before you will die of oxygen deprivation.",
      "If you could drive to the sun at a speed of 88.5 km/h (55 mp/h) it would take around 193 years",
      "If you counted 24 hours a day, it would take 31,688 years to reach one trillion!",
      "If you cut a 'V' shape into your toe nails, you can prevent 'in-grown' toe nails.",
      "if you filled a matchbox with gold it could be flattened into a sheet the size of a tennis court",
      "If you flip a coin ten times, the odds against its coming up with the same side showing each time are 1,023 to 1.",
      "If you put a raisin in a fresh glass of champagne, it will rise and fall continuously.",
      "If you shake a can of mixed nuts, the larger ones will rise to the top.",
      "If you took a standard slinky and stretched it out it would measure 87 feet.",
      "If you toss a penny 10,000 times, it will not be heads 5,000 times, but more like 4,950. The heads picture weighs more, so it ends up on the bottom.",
      "If you unfolded your brain, it would cover an ironing board.",
      "If you went out into space, you would explode before you suffocated because there's no air pressure.",
      "If you were to roll a lung from a human body and out flat it would be the size of a tennis court.",
      "If you yelled for 8 years, 7 months and 6 days, you would have produced enough sound energy to heat one cup of coffee.",
      "if your DNA was stretched out it would reach to the moon 6,000 times",
      "If your skin is laid flat it will cover an area of 18 square feet.",
      "If your stomach didn't produce a new layer of mucous every two weeks, it would digest itself.",
      "If you’re over 100 years old, there’s an 80% chance you’re a woman.",
      "In 1659, it was illegal to celebrate Christmas in Massachusetts.",
      "in 1878 the first telephone book made contained only 50 names",
      "In 1895 Hampshire police handed out the first ever speeding ticket, fining a man for doing 6mph!",
      "In 1897, Bayer, who is the maker of Aspirin, marketed the drug heroin.",
      "In 1910 football teams were penalized 15 yards for an incompleted forward pass.",
      "In 1954, Bob Hawke was immortalized by the Guinness Book of Records for chugging 2.5 pints of beer in 12 seconds.",
      "In 1976 an LA secretary named Jannene Swift officially married a 50 pound rock in a ceremony witnessed by more than 20 people.",
      "In 1980, a Las Vegas hospital suspended workers for betting on when patients would die!",
      "In 1980, the city of Detroit presented Saddam Hussein with a key to the city.",
      "In 1982, a high school student from Los Angeles, California unscrambled the Rubik's Cube in 22.95 seconds.",
      "In 1998, Sony accidently sold 700,000 camcorders that had the technology to see through people's clothes.",
      "In 1999, Pepsi, Inc. paid $0.00 in income tax!",
      "In 2004, The Japanese Ice Cream Association promoted “raw horse flesh” ice cream in hopes that it would boost the popularity of ice cream!",
      "In 32 years. there are about 1 billion seconds!",
      "in a deck of cards the king of hearts is the only king without a moustache",
      "In a year, the average person walks four miles to make his or her bed.",
      "in Africa more people are killed by crocodiles than lions",
      "In Albania, nodding your head means 'no' and shaking your head means 'yes'.",
      "In an average lifetime a person will walk the equivalent of three times around the world.",
      "In ancient China, people committed suicide by eating a pound of salt.",
      "In Ancient Greece, if a woman watched even one Olympic event, she was executed.",
      "In ancient Japan, public contests were held to see who could fart the loudest and longest!",
      "In ancient Rome it was considerfed a sign of leadership to be born with a crooked nose.",
      "In Athens, Greece, a driver's license can be taken away by law if the driver is deemed either unbathed or poorly dressed.",
      "In Australia, Burger King is called Hungry Jack's.",
      "In Bangladesh, kids as young as 15 can be jailed for cheating on their finals!",
      "In Belgium there is a museum just for strawberries.",
      "In Brazil, Christmas is celebrated with fireworks.",
      "In Cleveland, Ohio it is illegal to catch mice without a hunting license.",
      "In eastern Africa you can buy beer brewed from bananas",
      "In England, in the 1880's, Pants was considered a dirty word!",
      "In England, the Speaker of the House is not allowed to speak.",
      "In Florida, It is illegal to sing in a public place while attired in a swimsuit.",
      "In Florida, Penalty for horse theft is death by hanging.",
      "In France, it is legal to marry a dead person!",
      "In Gulliver's Travels Jonathan Swift described the two moons of Mars, Phobos and Deimos, giving their exact size and speeds of rotation. He did this more that a hundred years before either moon was discovered!",
      "In India the number of motorized vehicles have increased from 2 million in 1947 to 33 million in 199",
      "In Haiti, only 1 out of every 200 people own a car.",
      "In high school, Robin Williams was voted 'Least Likely to Succeed.",
      "In Holland, you can be fined for not using a shopping basket at a grocery store!",
      "In Idaho, You may not fish on a camel's back.",
      "In India the number of motorized vehicles have increased from 2 million in 1947 to 33 million in 199",
      "In India, Pajamas are accepted as standard daytime wearing apparel.",
      "In India the number of motorized vehicles have increased from 2 million in 1947 to 33 million in 199",
      "In India, people are legally allowed to marry a dog!",
      "In India the number of motorized vehicles have increased from 2 million in 1947 to 33 million in 199",
      "In India, pickled ginger, minced mutton, and a cottage cheese like substance are popular pizza toppings.",
      "In its ancient form, the carrot was purple, not orange.",
      "In just about every species of mammal, the female lives longer than the male.",
    ],
  };
  
const factRef = document.querySelector('.fact');
const generateButton = document.getElementById('generate');

generateButton.addEventListener('click', () => {
    factRef.textContent = factsObject.facts[Math.floor(Math.random() * factsObject.facts.length)]
})